### ISSUE TITLE
@prop(required: true) ignored on virtual properties

### ISSUE THREAD

**Issue by Noja13it** [szokodiakos/typegoose#240]
When using virtual properties, the required flag is not enforced.
For example:
```Javascript
@prop({required:true})
set password(cleartext: string) {...}
```
It's possible to create a new document without passing a "password" field.

**Comment by Drageaux** [comment]
Virtual is still very confusing to me in Typegoose. I'm gonna make a wild guess that you haven't written the getter. Say, your authenticator wouldn't be able to retrieve the password without 
```
@prop({required:true})
get password(){}
```
Seems like you're trying to disable retrieving a password for security purposes. That should be in the controller layer (where you fetch data), but you're in the model layer. The model ideally shouldn't know how you're hiding the password.

**Comment by hasezoey** [comment]
i would say, it is because: what @Drageaux said, and, a virtual property is *virtual* it is getting & setting as a function, means, it returns another value from `this` or getting from somewhere else, and because its a function, it is "always" there (and when you want to include it in .toJSON, you must activate it (more to that in the mongoose documentation))

**Comment by hasezoey** [comment]
im working on another issue, and found why this happenes:
in [prop.ts](https://github.com/szokodiakos/typegoose/blob/943c5890e5434f0c793d4dcff47a9fc9a4591794/src/prop.ts#L130) it returns, and does not apply an required flag/parameter/option

-> it could be made, but for that the `baseProp` function would need to be re-worked, because setting the required flag is done at the end, with other types & i dont know if mongoose even supports this

**Comment by hasezoey** [comment]
i think this can be closed as a "wontfix" because i could find any api of mongoose documenting the use of options in virtual's
https://mongoosejs.com/docs/api/schema.html#schema_Schema-virtual
-> this only accepts options for "virtual-populate"

@Ben305

**Comment by hasezoey** [comment]
@Ben305 Bump to close
