### ISSUE TITLE
[Question] Comparison to loadClass()

### ISSUE THREAD

**Issue by lonix1** [szokodiakos/typegoose#246]
Please forgive the new question.

Apparently mongoose allows creation of models from [ES6 classes](https://mongoosejs.com/docs/advanced_schemas.html#creating-from-es6-classes-using-loadclass).

I realise ES6 is not TypeScript. However I'm trying to decide which approach to take, and don't understand the benefits of each one.

Are there extra benefits to using typegoose that I won't get if I go with `loadClass()`?

**Comment by hasezoey** [comment]
duplicate of szokodiakos#48

**Comment by hasezoey** [comment]
<sub>I know this is an old question, but i will answer more detailed anyway</sub>

With version 6.0.0, typegoose uses `loadClass()`

What loadClass can do:
- load getters & setters
- load static methods
- load instance methods

What loadClass cannot do:
- make properties, that why `@prop` in typegoose exists
- make virtuals
- make schema Options as a decorator
- make indexes as a decorator

otherwise why i marked the issue as a duplicate at first, was a small mistake
but with v6.0.0 it is being used

@Ben305 this can be closed
