### ISSUE TITLE
Having troubles with required as function.

### ISSUE THREAD

**Issue by JohnatanNorman** [szokodiakos/typegoose#247]
Hi there! I wanted to declare required as a function and have this in my class:
```
  @prop({ default: false })
  public verified!: boolean
  @prop({
    required() {
      return !this.verified
    }
  })
  public verifiedToken?: string
```
Typescript tells me: 
> Property 'verified' does not exist on type 'PropOptionsWithValidate'.

Am I doing something wrong? In the docs it states that it supports same stuff as mongoose required.

**Comment by hasezoey** [comment]
> `public verified!: boolean`

you made `!` which makes it "required" in typescript, but no `required` option in `@prop`
your error `Property 'verified' does not exist on type 'PropOptionsWithValidate'.` has nothing todo with the required function

does this solve it?

**Comment by hasezoey** [comment]
https://github.com/szokodiakos/typegoose/blob/a3c7ceedc1e4818fe6282fef9218b23a00e73e74/src/prop.ts#L10-L12
https://github.com/szokodiakos/typegoose/blob/a3c7ceedc1e4818fe6282fef9218b23a00e73e74/src/prop.ts#L28-L31

these state that its possible, but currently there are no tests for it,
but it should work, because its just passed into mongoose, typegoose is not modifying it ...

**Comment by hasezoey** [comment]
@Ben305 this can be closed as "invalid" / "stale"

added a test in v6.0.0, and i had no problems
