### ISSUE TITLE
'immutable' option in @prop decorator missing in the types

### ISSUE THREAD

**Issue by naorzr** [szokodiakos/typegoose#320]
It seems like it's supported, but not updated in the prop.d.ts file.

**Comment by hasezoey** [comment]
Sorry for the late response for this issue:
i cant find a native "immutable" option in mongoose, but i can find `mongoose-immutable` module, and because this is **not** native mongoose, it will probably never be supported, but with the plugin and `// @ts-ignore` you can always add options that have no type

**Comment by naorzr** [comment]
@hasezoey it seems like they haven't updated their own .d.ts files, but it is a native feature.
please see https://mongoosejs.com/docs/api/schematype.html#schematype_SchemaType-immutable.

**Comment by hasezoey** [comment]
@naorzr sorry, but i meant that i couldnt find anything on google that would be related to the native one, only to the one module, but yes, it could be easily added ... when i find it documented correctly (.d.ts), i will add it

**Comment by hasezoey** [comment]
@Ben305 this can be closed because it is included in v6.0.0
