### ISSUE TITLE
[Question] How to add global methods like `paginate()`

### ISSUE THREAD

**Issue by wxs77577** [szokodiakos/typegoose#382]
I use a paginate plugin: https://www.npmjs.com/package/mongoose-paginate-v2

So I have to add a `paginate()` method in **all** models like this: 

```js
static paginate: (where: object, options: PaginateOptions) => Promise<PaginateResult<SiteSchema>>;
```

Is there any way to add this declaration globally?

**Comment by hasezoey** [comment]
as far as i can tell (from a rough look at the readme/doc of this module), it is global across all models, and only a model function, so you could make a base model that has this function and all others can extend from it(so that not every model/schema has to include the definition)

**Comment by wxs77577** [comment]
Thanks, but how could I pass `SiteSchema` to  the `BaseSchema` ?

**Comment by hasezoey** [comment]
i dont know what these schemas are (i couldnt find it in the supplied link), i can only generally say this:

typegoose cant extend normal schemas, at least not without the user doing something, like if its a 
plugin: the plugin functions must be defined in the class itself, 

if its a schema that should be added: use `buildSchema` and modify your schema, use `addModelToTypegoose` (version 6.0.0+), this function still needs a class for the type definitions, otherwise the point of typegoose is not used

**Comment by hasezoey** [comment]
@Ben305 this can be closed as "solved" / "fixed"

to give a final answer:
to use global methods, create a class that has the type on it, and any class that should have this type should extend it, and then apply the plugin globally to mongoose (i cant say for sure, because i dont work with plugins)
