### ISSUE TITLE
Support for compound indexes

### ISSUE THREAD

**Issue by jorge-recio** [szokodiakos/typegoose#43]
I have not found any reference about how to define compound indexes using Typegoose.
Is there any way to do it?

Thanks.

**Comment by szokodiakos** [comment]
Hello!

Thanks for your interest in Typegoose. Unfortunately currently field-level index definitions are supported, and to support compound indexes, schema level index definition is required.

It is currently a missing feature, but i will assign this as an enhancement and if I have the time it will be done.

PS: PR-s are also appreciated!

Akos

**Comment by jorge-recio** [comment]
Thanks for your quick response. I think it could be done whith a class level decorator like @indexes.

**Comment by kevin-frugier** [comment]
I would really fancy a solution in the direction @jorge-recio mentioned.
I'm new to Typescript (not JS) otherwise I would have done a PR that does just that.

In the meantime, for anyone in need of compound indexes, I've done a temporary **workaround** in a fork where indexes can be given as `indexes` in the `GetModelForClassOptions` param of the `getModelForClass` method : https://github.com/kevin-frugier/typegoose
I've added the `postinstall-build` package in my fork so it can be used "as such" from GitHub (since compilation to JS is required).

e.g:
```
const options: GetModelForClassOptions = ...;
options.indexes = [{ fields: { firstName: 1, lastName: 1 }, options: { unique: true } }];
const UserModel = new User().getModelForClass(User, options);
```

**Comment by carmas123** [comment]
How can I use your fork in my package.json?
I got an error when I use
"typegoose": "git+https://github.com/kevin-frugier/typegoose.git"

**Comment by paul42** [comment]
would it be possible to create an @index() decorator, but for the class level? I wouldn't mind taking a stab at a PR, but I'd need to learn a lot about decorators

**Comment by hasezoey** [comment]
thanks to #188 this can be closed

@Ben305
