### ISSUE TITLE
Populate across different DBs

### ISSUE THREAD

**Issue by danigomez** [szokodiakos/typegoose#44]
I have two DB  with a Mongoose instance for each one, which I use as an `existingMongoose` property when I create a new `getModelForClass` instance. 
In a model associated to the first Mongoose instance I have a ref to a model in the second Mongoose instance.
And of course, when I try to populate the ref of the first model (Which refers to the second Mongoose instance) I get a `MissingSchemaError: Schema hasn't been registered for model` because it is not registered in the first Mongoose instance.
This is supported by Mongoose (http://mongoosejs.com/docs/populate.html#cross-db-populate) but Typegoose expects a fully Mongoose instance, not a connection created with `createConnection` to associate a model to it.

Is there any workaround for this??

(I'm open to implement this if you give me some guidance :) )

**Comment by szokodiakos** [comment]
Hello! That was indeed a problem (I haven't really heard of this feature until now) and it made sense to implement it so that an existing connection could also be passed down.

I quickly tried out this and came to a conclusion that instead of `existingMongoose` ,`existingConnection` should be passed down (though `existingMongoose` still remains so no breaking change should occur).

I've tried it and it works. It was implemented in this commit https://github.com/szokodiakos/typegoose/commit/474dd13e99438781375be3e081037ae99c1113a1

Please try it and if something's off about it let me know. Closing this one.

Akos
