### ISSUE TITLE
GeoJSON Support

### ISSUE THREAD

**Issue by gkTim** [szokodiakos/typegoose#45]
Hi,

is it possible to use GeoJSON with Typegoose?
I'm not able to create an index so I can search it with $nearSphere.

What I've tried is to create the following model to store the data:

```
export class LocationData extends Typegoose {
    @prop()
    public type: string;

    @arrayProp({ items: Number })
    public coordinates: [number];
}
```

In my user model I have added the following attribute:

```
export class User extends Typegoose {
    @prop()
    public currentLocation: LocationData;
}
```

Since there must be an index on currentLocation to be able to perform the $nearSphere query I tried `@prop({index: true})`.

But I got the following error message:

```
TypeError: Undefined type `undefined` at `currentLocation.index`
  Did you try nesting Schemas? You can only nest using refs or arrays.
```

Some tutorials said you must define your own type to store the location data.
But how do I do it with Typegoose?

The mongoose way is:

```
var locationSchema = new Schema({  
  loc: {
    type: {
      type: "String",
      required: true,
      enum: ['Point', 'LineString', 'Polygon'],
      default: 'Point'
    },
    coordinates: [Number]
  }
});

locationSchema.index({ 'loc': '2dsphere' });
var Location = mongoose.model( 'Location', locationSchema );
```

What do I need to do to solve this issue?

**Comment by szokodiakos** [comment]
Hello. This could happen because of two reasons:
- To define an index required for geoJSON you must use schema wise index definition (?). If this is the case, so no line index can be used (when defining the schema) then this is currently not supported by Typegoose, however schema-level index definition is a requested feature so it will likely be developed if I have the time (https://github.com/szokodiakos/typegoose/issues/43).
- If it can be defined using prop-level index (like you did in the example), it is clearly a bug in Typegoose as the code should work.

Either way research must be made about geoJSON index (can it be defined in the schema property when using pure Mongoose). If it is possible then the bug must be eliminated in Typegoose.

Both researching and PRs are greatly appreciated, if you have the time. Otherwise when I'll have the time will look into it.

**Comment by hasezoey** [comment]
currently in the tests is 
https://github.com/szokodiakos/typegoose/blob/ea1c0ec6bbebdd6b27ba4580ec39c1d3535b2084/test/models/rating.ts#L8
and
https://github.com/szokodiakos/typegoose/blob/ea1c0ec6bbebdd6b27ba4580ec39c1d3535b2084/test/models/rating.ts#L19-L20

i dont know if this "fixes" the full issue here...

**Comment by naorzr** [comment]
@hasezoey @Ben305  I think this can be closed, I've tested it and it seems to be working just fine for this kind of query
```
{
    location: {
      $geoWithin: {
        $centerSphere: [[-122.5, 37.7], 300 / 3963.2]
      }
    }
}
```

**Comment by naorzr** [comment]
@hasezoey honestly it works just fine for the queries OP specified.

defining class like in the example you brought
```
@index({ location: '2dsphere' })
export class Rating extends Typegoose {
  @prop({ ref: Car })
  public car: Ref<Car>;

  @prop({ ref: User })
  public user: Ref<User>;

  @prop()
  public stars: number;

  @arrayProp({ items: Array })
  public location: [[number]];
}
```

and doing query search with $nearSphere.

**Comment by hasezoey** [comment]
i think this can now be closed as "solved"

@Ben305
