### ISSUE TITLE
Cannot set custom mongoose.Promise when using Typegoose

### ISSUE THREAD

**Issue by jakobwilkenson** [szokodiakos/typegoose#73]
I'm using typegoose 3.6.0 with mongoose 4.13.0.

Setting mongoose.Promise doesn't work when using Typegoose, even if setting it everywhere I import mongoose. As a result (I'm assuming) the mongoose promises are never executed. Removing Typegoose solves the problem.

Eveywhere I import mongoose:
```javascript
const mongoose = require("mongoose")
(<any>mongoose).Promise = global.Promise;
```

Defining the model:
```javascript
export enum Role {
    USER = "user",
    CONTRIBUTOR = "contributor",
    ADMIN = "admin"
}

export class UserProto extends Typegoose {
    _id: mongoose.Types.ObjectId;
    createdAt: Date;
    updatedAt: Date;

    @prop({ enum: Role, default: Role.USER })
    role: Role;
}

export const User = new UserProto().getModelForClass(UserProto, { schemaOptions: { timestamps: true }});
```

"in save" is never logged
```javascript
let user = new User({role: Role.USER});
user.save().then((doc) => {
      console.log("in save");
      
      return doc.toObject();
    }).catch((err) => {
      console.log("error");
    }); 
```

**Comment by woxixiulayin** [comment]
i got the same issue,  that's because in node_modules/typegoose, it has its own mongoose dependence。in your code， mongoose is different from  typegoose used from its own dependence.
you can delete the mongoose under node_modules/typegoose/node_modules to solve this.or use typegoose as local module, delete mongoose dependency. and do not put typegoose it in package.json.
this solution is not nice, i hope someone can fix this.

**Comment by Omegahorus** [comment]
I had some similar Problem with the mongoose. It didn't open the correct connection to the mongo-db and always told me to use not the default mongoose-Promise.

I fixed it with forwarding an existing mongoose model to typegoose.
```javascript
new User().getModelForClass(User, { existingMongoose: mongoose });
```

and setting the correct promise `(<any>mongoose).Promise = Promise;` is only in my main-app file (where I also open the connection).

Hope this solves your problem.

**Comment by jakobwilkenson** [comment]
Yes, passing through the existing mongoose works! Unfortunately I immediately ran into other issues and decided that the benefit of removing redundancy wasn't worth the cost of having another library with it's own complexities and issues so I removed typegoose.

**Comment by EricRabil** [comment]
This issue is caused by version conflicts between the version of `mongoose` that you require and the version of `mongoose` that `typegoose` requires. At the time of writing this, `typegoose` requires `mongoose@4.11.1`. Running  `npm install mongoose@4.11.1 --save` or `yarn add mongoose@4.11.1` will resolve this issue (note: you may need to clear your `node_modules` folder after so that the version conflicts are fully resolved)
